version: "3"

services:

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: dmanev
       POSTGRES_PASSWORD: Kjctr
       POSTGRES_DB: greetings

  greetings_app:
    image: python:3.7-rc
    restart: always
    container_name: greetings_app
    depends_on:
      - postgresql
    environment:
      DB_URL: postgresql://dmanev:Kjctr@postgresql:5432/greetings
    ports:
      - 5000:5000
    volumes:
      - ./greetings_app:/greetings_app
    command: bash -c "pip install -r /greetings_app/requirements.txt && python /greetings_app/app.py"
    
  nginx-proxy:
    image: nginx:latest
    restart: always
    container_name: nginx-proxy
    links:
      - greetings_app
    ports:
      - 80:8080
    volumes: 
      - ./ng_conf/nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/sh -c "nginx -g 'daemon off;'"
